#!/bin/bash
########################################################################
#
# 2011-01-20
# Jonas Pasche
# jpasche@jonaspasche.com
#
########################################################################
#
#       This program is free software: you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation, either version 3 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
#
# This script will update the qmail configuration regarding morercpthosts
# and virtualdomains out of their according configuration directories.
# It will also call all needed commands to make these changes come into
# effect immediately.

QMAIL_HOME=/var/qmail

emit_warning () {
  cat <<__EOF__ >> $1
#
# DO NOT EDIT! This file is auto-generated by $0
#

__EOF__
}


# create temporary file to prevent data loss on concurrent access
MRHTMP=`mktemp ${QMAIL_HOME}/control/morercpthosts.tmp.XXXXXX`   || exit 1
emit_warning ${MRHTMP}
# inherit ownership and permissions from the existing file
chown --reference=${QMAIL_HOME}/control/morercpthosts ${MRHTMP}  || exit 1
chmod --reference=${QMAIL_HOME}/control/morercpthosts ${MRHTMP}  || exit 1
# generate morercpthosts out of morercpthosts.d/* and run qmail-newmrh
( 
	ls -1 ${QMAIL_HOME}/control/morercpthosts.d >> ${MRHTMP} && \ 
	mv -f ${MRHTMP} ${QMAIL_HOME}/control/morercpthosts && \
	${QMAIL_HOME}/bin/qmail-newmrh && \
	chown --reference=${QMAIL_HOME}/control/morercpthosts ${QMAIL_HOME}/control/morercpthosts.cdb && \
	chmod --reference=${QMAIL_HOME}/control/morercpthosts ${QMAIL_HOME}/control/morercpthosts.cdb 
) || exit 1

# create temporary file to prevent data loss on concurrent access
VDTMP=`mktemp ${QMAIL_HOME}/control/virtualdomains.tmp.XXXXXX`   || exit 1
emit_warning ${VDTMP}
# inherit ownership and permissions from the existing file
chown --reference=${QMAIL_HOME}/control/virtualdomains ${VDTMP} || exit 1
# generate virtualdomains out of virtualdomains.d/* and give qmail-send a HUP
( 
	grep -r . ${QMAIL_HOME}/control/virtualdomains.d | awk -F / '{ print $NF }' >> ${VDTMP} && \
	mv -f ${VDTMP} ${QMAIL_HOME}/control/virtualdomains && \
	svc -h /service/qmail-send 
) || exit 1

