#!/bin/sh
########################################################################
#
# 2011-12-20
# Jonas Pasche
# jpasche@jonaspasche.com
#
########################################################################
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
#
# This script will enable an error_log for a Uberspace
#
########################################################################

source  /usr/local/sbin/uberspace-account-common

checkforrootprivs;

USAGE="Usage:\n-h\t\tthis help message\n-u string\tusername\n";

if [ ! $# -ge 1 ];
then
	printf "No arguments given.\n$USAGE" $(basename $0) >&2
	exit 2;
fi

## Parse arguments
while getopts ":hu:" Option; do
	case $Option in
		h	)
				printf "$USAGE" $(basename $0);
				exit 0;
			;;
		u	)
				checkusername ${OPTARG}
				USERNAMEGIVEN=1;
				USERNAME=${OPTARG};
			;;
		?	)
				printf "Invalid option or option without parameter: -${OPTARG}\n$USAGE" $(basename $0) >&2
				exit 2;
			;;
		*	)	# Default.
				printf "Unimplemented option: -${OPTARG}\n$USAGE" $(basename $0) >&2
				exit 2;
			;;
	esac
done

shift $(($OPTIND - 1))

if [ ! "$USERNAMEGIVEN" ];
then
	printf "No username given.\n$USAGE" $(basename $0) >&2
	exit 2;
fi

for CONF in /etc/httpd/conf.d/*.${USERNAME}.conf ; do
  grep -q ^ErrorLog $CONF
  if [ "$?" = "0" ] ; then
    echo "$CONF already has an error_log"
  else
    echo "changing $CONF";
    sed -i -e "s/^Include \/etc\/httpd\/conf\/dyncontent.conf/&\nErrorLog \/readonly\/${USERNAME}\/logs\/error_log/" ${CONF}
    ## this triggers a script that will restart httpd within the next five minutes
    touch /root/please_restart_httpd;
  fi
done

# old versions if this file are possibly immutable, but this is
# no longer needed due to the move to /readonly
chattr -i /readonly/${USERNAME}/etc/logrotate.conf
sed -i -e 's/access_log/*_log/;' /readonly/${USERNAME}/etc/logrotate.conf

echo -e "OK Alles erledigt"
