#!/bin/sh
########################################################################
# 2014-07-03 Moritz Werner mwerner@jonaspasche.com
########################################################################
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
# 2014-07-17 run checks as user
########################################################################

cd "$( dirname "${BASH_SOURCE[0]}" )"

# mutt needs this
export REPLYTO=hallo@uberspace.de
export SENDMAIL="mutt -F /usr/local/sbin/mails/.muttrc"

export HOSTNAME_SHORT=`hostname --short`

######## FUNCTIONS

checks_as_root(){
  UBERUSER=$1
  UBERHOME=$(eval echo ~${UBERUSER})
  UBERWEB=$(echo /var/www/virtual/${UBERUSER})
  MAILFILE=$(mktemp /tmp/uberspace-account-healthcheck.XXXXXX)

  for f in ./mails/*; do source $f; done
  
  for f in ./checks/user_as_root/enabled/*; do source $f; done

  rm -f ${MAILFILE}
}

checks_as_user(){
  UBERUSER=$(whoami)
  UBERHOME=$(eval echo ~${UBERUSER})
  UBERWEB=$(echo /var/www/virtual/${UBERUSER})
  MAILFILE=$(mktemp /tmp/uberspace-account-healthcheck.XXXXXX)

  for f in ./mails/*; do source $f; done

  for f in ./checks/user_as_user/enabled/*; do source $f; done

  rm -f ${MAILFILE}
}
# export it, so it can be called by su
export -f checks_as_user

######## CHECKS

#### Host checks
for f in ./checks/host/enabled/*; do source $f; done

#### User checks
for CONF in `find /etc/httpd/conf.d -name "virtual.*.conf" -printf "%f\n"` ; do
  UBERUSER=`echo $CONF | sed 's/^virtual\.//; s/\.conf$//;'`

  # on mixed hosts: make sure that only Uberspace.de users will be checked
  if [ ! -e /var/qmail/control/virtualdomains.d/${UBERUSER}.${HOSTNAME_SHORT}.uberspace.de ] ; then
    continue
  fi


  OWNER=$(stat -c '%U' /home/${UBERUSER})

  if [ "${OWNER}" != "root" ] ; then

    # checks as user
    su ${UBERUSER} -s /bin/bash -c 'checks_as_user'

    # checks as root
    checks_as_root $UBERUSER
  fi

done

